### PR TITLE
feat: Enhance more beautiful valid text alerts by using modal

### PR DESCRIPTION
**Pull request by Armakuji**
## Related Issue or bug

Fixes: #26

#### Describe the changes you've made
 - add valid text modal
 - add some css

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

| Original | Updated |
| ------------- | ------------- |
| Screen Shot 2021-10-03 at 3 29 15 PM | Screen Shot 2021-10-03 at 3 29 50 PM |

### CODE REVIEW

**Comment by jatiinyadav** [comment]
1. When someone hovers on the cross, the cursor should be a pointer.
2. Do the styling changes in the **style.scss** file not in **style.css**.
3. Resolve the conflicts.

**Comment by Armakuji** [comment]
OK, Thanks for your review. I will fix that.

**Comment by Armakuji** [comment]
@jatiinyadav I fixed all the comments ✨. Please review again.

**Comment by jatiinyadav** [comment]
@Armakuji Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
